vulekamali/static-budget-portal

- _data/2015-16/national/departments/planning-monitoring-and-evaluation.yaml
- _data/2016-17/national/departments/planning-monitoring-and-evaluation.yaml
I add the Missing datasets (.xls and .pdf) for the department of Planning, Monitoring and Evaluation
>  add missing datasets

- 2015-16/index.md
- 2016-17/index.md
- 2017-18/index.md
- _data/2015-16/index.yaml
- _data/2016-17/index.yaml
- _data/2017-18/departments.yaml
- _data/2017-18/index.yaml
- _data/index.yaml
- generate/from_dynamic.py
- index.md
/ is a copy of the latest financial year page details
> Generate financial-year pages

- _includes/utilities/html/scripts.html
This prevents errors from being reported in dev mode
> Don't use GA in dev mode

- Gemfile
- Gemfile.lock
- _config.yml
Automatically generate a full sitemap.xml
> Generate a sitemap

- robots.txt
https://wummel.github.io/linkchecker/faq.html
https://stackoverflow.com/questions/33617859/disallow-all-for-all-user-agents-except-one-user-agent
> Allow linkchecker

- _data/2015-16/government_functions.yaml
- _data/2015-16/index.yaml
- _data/2016-17/government_functions.yaml
- _data/2016-17/index.yaml
- _data/2017-18/government_functions.yaml
- _data/2017-18/index.yaml
- _includes/components/homepage/Expenditure/index.html
- _layouts/homepage.html
That means manually adding the data for it because we don't have this dataset in the data infrastructure at the moment.
> Use consolidated expenditure for spending by function

- _data/2015-16/manual_resources.yaml
- _data/2016-17/manual_resources.yaml
- _data/2017-18/manual_resources.yaml
- _includes/components/homepage/Links/index.html
- _layouts/homepage.html
> Adds logic to determine treasury URL for homepage resources

- _data/2018-19/government_functions.yaml
- _data/2018-19/manual_resources.yaml
**IMPORTANT**: `budget_revenue_data` still needs to be added.
> Adds manual data

- _includes/components/about-and-learning-centre/Events/index.html
- _layouts/events.html
> Fixes issue with call to actions

- _includes/components/universal/Graph/index.html
@jbothma please review for correctness.
> Updated wording for programme charts

- _layouts/faq.html
- _layouts/homepage.html
> Fixes spacing on homepage and FAQ page

- 404.md
- _data/error-404.yaml
- _layouts/error-404.html
> Adds 404 page

- _layouts/department.html
> Adds call to action

- _data/2018-19/provincial/free-state/departments/agriculture-and-rural-development.yaml
- _data/2018-19/provincial/free-state/departments/human-settlements.yaml
- _data/2018-19/provincial/free-state/departments/sport-arts-culture-and-recreation.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/agriculture-and-rural-development.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/arts-and-culture.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/co-operative-governance-and-traditional-affairs.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/community-safety-and-liaison.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/education.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/health.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/human-settlements.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/office-of-the-premier.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/provincial-legislature.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/provincial-treasury.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/public-works.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/social-development.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/sport-and-recreation.yaml
- _data/2018-19/provincial/kwazulu-natal/departments/transport.yaml
Rebuild with KZN after I fixed a typo in the KZN data resulting in them not getting the quantitative summaries before.
3 Free State budgets are included because their datasets weren't indexed properly initially.
> Rebuild fixed kzn

- _data/2018-19/epres.yaml
@schalkventer not sure whether there's more to do under this in the frontend - I think regarding data we just need to remove this file since it's unused when there's detailed data available 
This is under https://www.pivotaltracker.com/story/show/156082312
> Clean up full EPREs file now we have provincial budget detail data

- _layouts/department.html
See comment in Pivotal: [https://www.pivotaltracker.com/story/show/156719963](https://www.pivotaltracker.com/story/show/156719963).
> Fixes issue with Discourse comment ID's

- _data/videos.yaml
> Add an additional video to vulekamali

- _layouts/contributed-data.html
> Adds additional overview text to contributed data listing page

- _includes/components/contributed-data/CsoRequest/index.html
- _includes/components/department-budgets/ContributedData/index.html
- _layouts/contributed_dataset.html
> Send users to ckan to contribute data

- _includes/components/header-and-footer/Footer/index.html
- _layouts/base.html
> Add link to Newsflash archive

- _includes/components/universal/Participate/partials/jul.html
- _includes/components/universal/Participate/partials/jun.html
> Correction to june participation

- robots.txt
> Disallow robots from visiting search page

- _data/events.yaml
> Update event dates.

- _layouts/government_dataset_category.html
> Fix link to dataset guide on category page

- _data/datasets/conditional-grant-frameworks/2018-19-community-library-services-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-comprehensive-agricultural-support-programme-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-education-infrastructure-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-hiv-and-aids-life-skills-education-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-ilima-letsema-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-land-care-programme-grant-framework-poverty-relief-and-infrastructure.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-learners-with-profound-intellectual-disabilities-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-maths-science-and-technology-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-national-school-nutrition-programme-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/2018-19-school-infrastructure-backlogs-grant-framework.yaml
- _data/datasets/conditional-grant-frameworks/index.yaml
- _data/datasets/contributed.yaml
- _data/datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17.yaml
- _data/datasets/contributed/budget-brief-eastern-cape-department-of-education-2018-19.yaml
- _data/datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15.yaml
- _data/datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15.yaml
- _data/datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2016-17.yaml
- _data/datasets/index.yaml
- _layouts/government_dataset_category.html
- datasets/conditional-grant-frameworks.md
- datasets/conditional-grant-frameworks/2018-19-community-library-services-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-comprehensive-agricultural-support-programme-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-education-infrastructure-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-hiv-and-aids-life-skills-education-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-ilima-letsema-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-land-care-programme-grant-framework-poverty-relief-and-infrastructure.html
- datasets/conditional-grant-frameworks/2018-19-learners-with-profound-intellectual-disabilities-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-maths-science-and-technology-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-national-school-nutrition-programme-grant-framework.html
- datasets/conditional-grant-frameworks/2018-19-school-infrastructure-backlogs-grant-framework.html
> Add some of the 2018-19 grant frameworks

- _includes/components/about/Background/index.html
- _includes/components/about/Contacts/index.html
- _includes/components/about/DataScientists/index.html
- _includes/components/about/Progress/index.html
- _includes/components/events/Events/index.html
- _includes/components/header-and-footer/ExtraFooter/index.html
- _includes/components/homepage/NewIntro/index.html
- _layouts/events.html
- _layouts/faq.html
- _layouts/homepage.html
- _layouts/terms-and-conditions.html
This is part of the updated brand guideline.
> Capitalise V for Vulekamali

- generate/from_dynamic.py
- index.md
> Manual override index.md data

- _includes/utilities/html/head.html
- _includes/utilities/html/scripts.html
- _layouts/base.html
> Switch to Google Tag Manager proper

- _includes/utilities/html/head.html
- _includes/utilities/html/scripts.html
- _layouts/base.html
Reverts OpenUpSA/static-budget-portal#463
It's logging page views twice so rather reverting til I can debug
> Revert "Switch to Google Tag Manager proper"

- _includes/scenes/department/ExpenditureMultiplesSection/index.html
- _includes/scenes/department/ExpenditurePhaseSection/index.html
https://www.pivotaltracker.com/story/show/163548707
> Fix explanation of budget adjustments

- _data/events.yaml
- _includes/components/events/Events/index.html
- _includes/scenes/homepage/EventSection/index.html
> Update to show northern cape events

- guides/frameworks-for-conditional-grants-to-provinces.md
https://www.pivotaltracker.com/n/projects/2092981/stories/163184137
> Datasets heading space update

- .gitignore
- Vagrantfile
This should bring up a usable instance with `vagrant up`.
> Add basic Vagrant config

- _includes/components/about/Contacts/index.html
https://www.pivotaltracker.com/n/projects/2092981/stories/164594252
> Raquel Ferreira: Removed 'Acting' from the title.

- _data/2016-17/consolidated.yaml
- _data/2017-18/consolidated.yaml
- _data/2018-19/consolidated.yaml
- _data/2019-20/consolidated.yaml
- generate/from_dynamic.py
- json/2016-17/consolidated.json
- json/2017-18/consolidated.json
- json/2018-19/consolidated.json
- json/2019-20/consolidated.json
Adds:
- consolidated YAML files
- consolidated JSON files
- code to generate YAML files
> Consolidated chart data

- _layouts/homepage.html
Remove lines on homepage.html with regards to Preview component as per Trello card
> remove lines from homepage_html to remove features

- README.md
- Vagrantfile
This adds Vagrant to the README.
This also removes `--incremental` as a usage recommendation, since it's not reliable enough (via @jbothma).
> Vagrant instructions

- packages/webapp/src/views/FocusArea/Markup.jsx
Removed shareable button on focus area pages.
> remove anchor property as no need to show share button

- packages/webapp/src/views/FocusArea/Markup.jsx
> Add extra footnote hardcoded

- packages/webapp/src/views/FocusArea/Markup.jsx
Move hardcoded footer outside of loop
> Static footer to appear only once and not inside of loop

- Vagrantfile
This should fix the "yarn build" memory exhaustion, for now.
> Bump Vagrant memory to 1 GB
